name: Linux C++ make-specs
'on':
  workflow_dispatch:
    inputs:
      extra_resolve_options:
        description: Extra Resolve Options
        required: false
  schedule:
  - cron: 0 1 * * *
  push:
    branches:
    - master
  pull_request:
jobs:
  docker_builds:
    timeout-minutes: 45
    strategy:
      fail-fast: false
      matrix:
        config:
        - container: ghcr.io/steinwurf/gcc-12:2.1.0
          cxx_mkspec: --cxx_mkspec=cxx_gxx123_x64
          name: GCC 12
        - container: ghcr.io/steinwurf/clang-15:2.1.0
          name: Clang 15
          cxx_mkspec: --cxx_mkspec=cxx_clang150_x64
        - container: ghcr.io/steinwurf/clang-15:2.1.0
          cxx_mkspec: --cxx_mkspec=cxx_clang15_address_sanitizer_x64
          name: Clang 15 Address Sanitizer
        - container: ghcr.io/steinwurf/clang-15:2.1.0
          cxx_mkspec: --cxx_mkspec=cxx_clang15_thread_sanitizer_x64
          name: Clang 15 Thread Sanitizer
    runs-on:
    - self-hosted
    - docker
    - builder
    name: ${{ matrix.config.name }}
    container:
      image: ${{ matrix.config.container }}
      options: --user 0:0
      volumes:
      - /home/buildbot/.ssh:/root/.ssh
    steps:
    - name: Checkout source code
      uses: actions/checkout@v3
    - name: Waf Configure
      env:
        EXTRA_RESOLVE_OPTIONS: ${{ inputs.extra_resolve_options }}
      uses: nick-fields/retry@v2
      with:
        max_attempts: 3
        timeout_minutes: 15
        command: python3 waf configure --git_protocol=git@ ${{ matrix.config.cxx_mkspec }} ${{ env.EXTRA_RESOLVE_OPTIONS }}
    - name: Waf Build
      run: |
        echo "::add-matcher::.github/gcc-problem-matcher.json"
        python3 waf
    - name: Waf Test
      run: python3 waf --run_tests
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true
